# -*- coding: utf-8 -*-
"""Untitled142.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGPzrJ9oW8NnW7oF7quJi7W-g698qd1D
"""

# src/data_loader.py
import pandas as pd
import json

def load_lecture_notes(filepath):
    with open(filepath, 'r') as file:
        data = json.load(file)
    return data

def load_milestone_papers(filepath):
    return pd.read_csv(filepath)

def preprocess_text(text):
    # Add any text preprocessing steps here (e.g., lowercasing, removing stop words)
    return text.lower()

def main():
    lecture_notes_path = '../data/lecture_notes.json'
    milestone_papers_path = '../data/milestone_papers.csv'

    lecture_notes = load_lecture_notes(lecture_notes_path)
    milestone_papers = load_milestone_papers(milestone_papers_path)

    # Preprocess the text data
    for note in lecture_notes:
        note['content'] = preprocess_text(note['content'])

    milestone_papers['summary'] = milestone_papers['summary'].apply(preprocess_text)

    # Save preprocessed data if needed
    with open('../data/processed_lecture_notes.json', 'w') as file:
        json.dump(lecture_notes, file)

    milestone_papers.to_csv('../data/processed_milestone_papers.csv', index=False)

if __name__ == "__main__":
    main()